---
- name: krevor ec2 stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import vpc setup variables
      include_vars: vars/output_vars

    - name: import krevor stack variables
      include_vars: vars/krevorstacksetup

    - name: create ec2 key
      ec2_key:
        name: krevorkey
        region: "{{region}}"
      register: krevorkey_out

    - name: save krevor key into loginkey_krevor.pem
      copy:
        content: "{{krevorkey_out.key.private_key}}"
        dest: "./loginkey_krevor.pem"
        mode: 0600
      when: krevorkey_out.changed

    - name: Create security group for ELB(Elastic Load Balancer)
      amazon.aws.ec2_security_group:
        name: krevorELB-sg
        description: allow port 80 from everywhere and all ports from sg
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
      register: krevorELBSG_out


