---
- name: krevor ec2 stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import vpc setup variables
      include_vars: vars/output_vars

    - name: import krevor stack variables
      include_vars: vars/krevorstacksetup

    - name: create ec2 key
      ec2_key:
        name: krevorkey
        region: "{{region}}"
      register: krevorkey_out

    - name: save krevor key into loginkey_krevor.pem
      copy:
        content: "{{krevorkey_out.key.private_key}}"
        dest: "./loginkey_krevor.pem"
        mode: 0600
      when: krevorkey_out.changed

    - name: Create security group for ELB(Elastic Load Balancer)
      amazon.aws.ec2_security_group:
        name: krevorELB-sg
        description: allow port 80 from everywhere and all ports from sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
      register: krevorELBSG_out

    - name: Create security group for krevor stack
      amazon.aws.ec2_security_group:
        name: krevorstack-sg
        description: allow port 80 from everywhere and all ports from sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: tcp
            ports:
              - 80
            rule_desc: allow all on port 80
            group_id: "{{krevorELBSG_out.group_id}}"


          - proto: tcp
            ports:
              - 22
            rule_desc: allow all on port 22
            group_id: "{{BastionSGid}}"
      register: krevorstackSG_out

    - name: update security group with own sg id
      amazon.aws.ec2_security_group:
        name: krevorstack-sg
        description: allow port 22k from everywhere and all ports from sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{krevorstackSG_out.group_id}}"




